// Generated by CoffeeScript 1.10.0
(function() {
  var Lock;

  Lock = require('redis-lock');

  module.exports = function(client) {
    var l;
    l = Lock(client);
    return function(req, res, next) {
      if (!res._redisLocks) {
        res._redisLocks = res._redisLocks || {};
        res.lock = function(lockName, next) {
          l(lockName, function(done) {
            res._redisLocks[lockName] = done;
            return next();
          });
          return res.once('finish', function() {
            return res.unlock(lockName);
          });
        };
        res.unlock = function(lockName) {
          var unlock;
          unlock = res._redisLocks[lockName];
          if (unlock) {
            delete res._redisLocks[lockName];
            return unlock();
          }
        };
      }
      return next();
    };
  };

}).call(this);
